const String sharedPrefUIDKey = 'uid';

String? uid;

// TODO remove this. It is for testing only.
String loremIpsum =
    """ Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc a congue justo, id laoreet tellus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Morbi euismod semper ante et iaculis. Aliquam sed ligula ultrices, mollis purus eget, fringilla turpis. In urna nunc, vestibulum eu luctus eget, tristique nec libero. Curabitur porta vel quam sed vehicula. Vivamus blandit erat nisl, ut euismod risus convallis nec. Ut porttitor elit eget diam ornare commodo vitae tincidunt mi. Donec placerat eros diam, eu volutpat ligula aliquet id. Phasellus finibus mi quis ullamcorper tristique. Proin at mauris mi. Nulla semper varius maximus. Fusce tempor interdum finibus. Vivamus varius odio ut gravida blandit. Integer feugiat purus urna, non venenatis elit laoreet eu.

Sed nec ipsum eget nisi consectetur fermentum. Fusce rutrum sagittis massa non ornare. Fusce semper est id consectetur gravida. Curabitur aliquam fermentum blandit. Nulla tristique felis in elementum venenatis. Maecenas dignissim eu nunc in lobortis. Praesent ex lorem, tempus non pretium et, placerat in ligula. Proin id velit maximus tellus molestie tincidunt luctus ac felis. Etiam at velit tellus. Nulla a ultricies ipsum. Sed vitae iaculis ligula.

Nullam non tortor at nulla eleifend egestas vitae lacinia ipsum. Vivamus tristique odio elit, id viverra massa iaculis in. Pellentesque mollis vel tortor nec elementum. Morbi quam sem, vehicula id mattis sed, maximus at augue. Aliquam sem ante, efficitur sit amet risus vel, lacinia pretium tellus. Aliquam sed felis eget enim imperdiet suscipit nec vitae tortor. Mauris mollis laoreet rhoncus. Aliquam et pharetra ex. Vestibulum blandit interdum metus eu convallis. Aliquam id tincidunt est, eget dignissim justo. Sed in justo quis metus tincidunt lobortis.

Aenean in massa non metus blandit luctus non vel ante. Morbi eu placerat urna. Aliquam fermentum dui dapibus, mattis arcu et, sagittis felis. Suspendisse rhoncus imperdiet nisi, ac porta turpis pulvinar nec. Praesent bibendum nibh nec leo finibus, at interdum nisl fermentum. Curabitur dictum orci eu quam aliquam, in ultrices nulla lacinia. Donec mattis, odio non dignissim aliquet, lacus nulla mattis lorem, ac aliquam nibh mi a enim. Nulla vel sodales nisi. Nunc iaculis libero nec ipsum semper tincidunt. Phasellus condimentum porta nisl, pharetra lobortis augue malesuada et. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nullam venenatis, dui id eleifend accumsan, est dui hendrerit ante, nec elementum leo risus at mauris. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum quis enim eu purus lobortis hendrerit eget eu lectus. Vivamus faucibus quis ipsum ut eleifend. Donec justo tellus, vulputate non varius et, ullamcorper in magna.

Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec tincidunt, justo id pulvinar consectetur, dolor odio pharetra sapien, vitae ullamcorper ex eros non nulla. Donec et nisi fermentum, aliquet magna et, dignissim diam. Curabitur porttitor facilisis pretium. In fermentum malesuada lorem, a lacinia augue placerat et. Etiam id lacus in mi interdum rutrum eget quis mi. Nulla at dapibus arcu. Nullam euismod blandit lectus, sit amet semper dui dapibus nec. Suspendisse facilisis maximus posuere. Nunc convallis risus eu nibh blandit, faucibus tincidunt massa varius. Donec efficitur eros nulla, sed tincidunt urna hendrerit eu. Mauris erat diam, ornare tristique convallis sit amet, dictum vitae leo. Praesent sapien libero, fringilla et augue vel, tincidunt eleifend orci. Integer egestas dolor quam, vitae ullamcorper urna mollis vitae.""";
